Module Module1

    Sub Main()
        Console.Title = "MsgBoxStyle.WTF"
        Console.ForegroundColor = ConsoleColor.Yellow
        Console.Clear()
        Console.WriteLine("MsgBoxStyle.WTF")
        Console.WriteLine()
        Console.WriteLine("MessageBox utilizzate nello sticker pack MsgBoxStyle.WTF su Telegram (https://t.me/addstickers/MsgBoxWTF)")
        MsgBox("Vuoi ristabilire il comunismo?", Microsoft.VisualBasic.MsgBoxStyle.YesNo, "MsgBoxStyle.WTF")
        MsgBox("Sei autistico", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Gay chi legge", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("È stato rilevato un eccesso di cromosomi", Microsoft.VisualBasic.MsgBoxStyle.Critical, "MsgBoxStyle.WTF")
        MsgBox("Porco Dio", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Smettila di segarti sugli hentai", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Fai schifo", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Hai vinto un iPhone XS Max da 512GB", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Madonna puttana", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Ti meriti una ginocchiata sui coglioni", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Qualcuno ha una corda?", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Impossibile continuare - È stata rilevata la presenza di un coglione", Microsoft.VisualBasic.MsgBoxStyle.Critical, "MsgBoxStyle.WTF")
        MsgBox("La persona sopra è ritardata", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Quanti cromosomi hai? Sono più di 300 vero?", Microsoft.VisualBasic.MsgBoxStyle.YesNo, "MsgBoxStyle.WTF")
        MsgBox("Se non la smettete di rompere il cazzo vi prendo a cinghiate sui denti Dio cancro", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Chi gioca a Fortnite è U L T R A  G A Y", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Se dici a qualcuno che la sua waifu fa schifo, tu fai ancora più schifo", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Questa cosa è ripugnante Dio idrovolante e Madonna rotante", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("AVVISO - È stato scoperto che neanche i PC della NASA possono calcolare il cazzo che me ne frega", Microsoft.VisualBasic.MsgBoxStyle.Exclamation, "MsgBoxStyle.WTF")
        MsgBox("La persona sotto è più inutile di una forchetta nella minestra", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Suicidio in corso... Si prega di non distrurbare l'interessato", Microsoft.VisualBasic.MsgBoxStyle.OkOnly, "MsgBoxStyle.WTF")
        MsgBox("Questo meme è ora di mia proprietà", Microsoft.VisualBasic.MsgBoxStyle.Exclamation, "MsgBoxStyle.WTF")
        Console.WriteLine()
        Console.WriteLine("Sticker creati da @LeddaZ")
        Console.ReadKey()
    End Sub
End Module
